/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.allocation;

import static my.allocation.EntryPage.apron_domestic;
import static my.allocation.EntryPage.apron_international;
import static my.allocation.EntryPage.apron_cargo;
import static my.allocation.EntryPage.pm1;
import static my.allocation.EntryPage.pm2;
import static my.allocation.EntryPage.pm3;

/**
 *
 * @author Windows-8 (x64)
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menu");
        jLabel1.setOpaque(true);

        jButton1.setText("Add plane to Apron");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("View Apron Status:");
        jLabel3.setOpaque(true);

        jButton2.setText("Domestic Passenger Apron");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("International Passenger Apron");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cargo Apron");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Remove plane from Apron");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Add plane to Database");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hello ADMIN");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/allocation/image/menu.jpg"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Manage Apron Area:");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Manage Planes Database:");
        jLabel5.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Alter users:");
        jLabel7.setOpaque(true);

        jButton8.setText("Register");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Un-Register");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Remove plane from Database");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("View Messages from USERS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Messages from USERS:");
        jLabel8.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Activity Logs:");
        jLabel11.setOpaque(true);

        jButton12.setText("View Activity Log");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Emergency Allocation:");
        jLabel12.setOpaque(true);

        jButton13.setText("Allocate Apron in emergency");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(248, 248, 248)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(38, 38, 38))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/allocation/image/sky.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        EntryPage UI=new EntryPage();                
        UI.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        Home h=new Home();
        h.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        pm1.setVisible(true);
        
        if(apron_domestic[0]!=0)
        {
            pm1.jLabel1.setForeground(java.awt.Color.red);
            pm1.jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel1.setForeground(java.awt.Color.green);
            pm1.jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[1]!=0)
        {
            pm1.jLabel2.setForeground(java.awt.Color.red);
            pm1.jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel2.setForeground(java.awt.Color.green);
            pm1.jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[2]!=0)
        {
            pm1.jLabel3.setForeground(java.awt.Color.red);
            pm1.jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel3.setForeground(java.awt.Color.green);
            pm1.jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[3]!=0)
        {
            pm1.jLabel4.setForeground(java.awt.Color.red);
            pm1.jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel4.setForeground(java.awt.Color.green);
            pm1.jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[4]!=0)
        {
            pm1.jLabel5.setForeground(java.awt.Color.red);
            pm1.jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel5.setForeground(java.awt.Color.green);
            pm1.jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[5]!=0)
        {
            pm1.jLabel6.setForeground(java.awt.Color.red);
            pm1.jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel6.setForeground(java.awt.Color.green);
            pm1.jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[6]!=0)
        {
            pm1.jLabel7.setForeground(java.awt.Color.red);
            pm1.jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel7.setForeground(java.awt.Color.green);
            pm1.jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[7]!=0)
        {
            pm1.jLabel8.setForeground(java.awt.Color.red);
            pm1.jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel8.setForeground(java.awt.Color.green);
            pm1.jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[8]!=0)
        {
            pm1.jLabel9.setForeground(java.awt.Color.red);
            pm1.jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel9.setForeground(java.awt.Color.green);
            pm1.jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[9]!=0)
        {
            pm1.jLabel10.setForeground(java.awt.Color.red);
            pm1.jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel10.setForeground(java.awt.Color.green);
            pm1.jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[10]!=0)
        {
            pm1.jLabel11.setForeground(java.awt.Color.red);
            pm1.jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel11.setForeground(java.awt.Color.green);
            pm1.jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[11]!=0)
        {
            pm1.jLabel12.setForeground(java.awt.Color.red);
            pm1.jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel12.setForeground(java.awt.Color.green);
            pm1.jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[12]!=0)
        {
            pm1.jLabel13.setForeground(java.awt.Color.red);
            pm1.jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel13.setForeground(java.awt.Color.green);
            pm1.jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[13]!=0)
        {
            pm1.jLabel14.setForeground(java.awt.Color.red);
            pm1.jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel14.setForeground(java.awt.Color.green);
            pm1.jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[14]!=0)
        {
            pm1.jLabel15.setForeground(java.awt.Color.red);
            pm1.jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel15.setForeground(java.awt.Color.green);
            pm1.jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[15]!=0)
        {
            pm1.jLabel16.setForeground(java.awt.Color.red);
            pm1.jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel16.setForeground(java.awt.Color.green);
            pm1.jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[16]!=0)
        {
            pm1.jLabel17.setForeground(java.awt.Color.red);
            pm1.jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel17.setForeground(java.awt.Color.green);
            pm1.jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[17]!=0)
        {
            pm1.jLabel18.setForeground(java.awt.Color.red);
            pm1.jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel18.setForeground(java.awt.Color.green);
            pm1.jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[18]!=0)
        {
            pm1.jLabel19.setForeground(java.awt.Color.red);
            pm1.jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel19.setForeground(java.awt.Color.green);
            pm1.jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[19]!=0)
        {
            pm1.jLabel20.setForeground(java.awt.Color.red);
            pm1.jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel20.setForeground(java.awt.Color.green);
            pm1.jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        
        if(apron_domestic[20]!=0)
        {
            pm1.jLabel21.setForeground(java.awt.Color.red);
            pm1.jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel21.setForeground(java.awt.Color.green);
            pm1.jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[21]!=0)
        {
            pm1.jLabel22.setForeground(java.awt.Color.red);
            pm1.jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel22.setForeground(java.awt.Color.green);
            pm1.jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[22]!=0)
        {
            pm1.jLabel23.setForeground(java.awt.Color.red);
            pm1.jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel23.setForeground(java.awt.Color.green);
            pm1.jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[23]!=0)
        {
            pm1.jLabel24.setForeground(java.awt.Color.red);
            pm1.jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel24.setForeground(java.awt.Color.green);
            pm1.jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[24]!=0)
        {
            pm1.jLabel25.setForeground(java.awt.Color.red);
            pm1.jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel25.setForeground(java.awt.Color.green);
            pm1.jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[25]!=0)
        {
            pm1.jLabel26.setForeground(java.awt.Color.red);
            pm1.jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel26.setForeground(java.awt.Color.green);
            pm1.jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[26]!=0)
        {
            pm1.jLabel27.setForeground(java.awt.Color.red);
            pm1.jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel27.setForeground(java.awt.Color.green);
            pm1.jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[27]!=0)
        {
            pm1.jLabel28.setForeground(java.awt.Color.red);
            pm1.jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel28.setForeground(java.awt.Color.green);
            pm1.jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[28]!=0)
        {
            pm1.jLabel29.setForeground(java.awt.Color.red);
            pm1.jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel29.setForeground(java.awt.Color.green);
            pm1.jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[29]!=0)
        {
            pm1.jLabel30.setForeground(java.awt.Color.red);
            pm1.jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel30.setForeground(java.awt.Color.green);
            pm1.jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[30]!=0)
        {
            pm1.jLabel31.setForeground(java.awt.Color.red);
            pm1.jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel31.setForeground(java.awt.Color.green);
            pm1.jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[31]!=0)
        {
            pm1.jLabel32.setForeground(java.awt.Color.red);
            pm1.jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel32.setForeground(java.awt.Color.green);
            pm1.jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[32]!=0)
        {
            pm1.jLabel33.setForeground(java.awt.Color.red);
            pm1.jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel33.setForeground(java.awt.Color.green);
            pm1.jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[33]!=0)
        {
            pm1.jLabel34.setForeground(java.awt.Color.red);
            pm1.jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel34.setForeground(java.awt.Color.green);
            pm1.jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[34]!=0)
        {
            pm1.jLabel35.setForeground(java.awt.Color.red);
            pm1.jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel35.setForeground(java.awt.Color.green);
            pm1.jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[35]!=0)
        {
            pm1.jLabel36.setForeground(java.awt.Color.red);
            pm1.jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel36.setForeground(java.awt.Color.green);
            pm1.jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[36]!=0)
        {
            pm1.jLabel37.setForeground(java.awt.Color.red);
            pm1.jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel37.setForeground(java.awt.Color.green);
            pm1.jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[37]!=0)
        {
            pm1.jLabel38.setForeground(java.awt.Color.red);
            pm1.jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel38.setForeground(java.awt.Color.green);
            pm1.jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[38]!=0)
        {
            pm1.jLabel39.setForeground(java.awt.Color.red);
            pm1.jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel39.setForeground(java.awt.Color.green);
            pm1.jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_domestic[39]!=0)
        {
            pm1.jLabel40.setForeground(java.awt.Color.red);
            pm1.jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm1.jLabel40.setForeground(java.awt.Color.green);
            pm1.jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        
        pm1.jLabel1.setText(" "+String.valueOf(apron_domestic[0])+" ");
        pm1.jLabel2.setText(" "+String.valueOf(apron_domestic[1])+" ");
        pm1.jLabel3.setText(" "+String.valueOf(apron_domestic[2])+" ");
        pm1.jLabel4.setText(" "+String.valueOf(apron_domestic[3])+" ");
        pm1.jLabel5.setText(" "+String.valueOf(apron_domestic[4])+" ");
        pm1.jLabel6.setText(" "+String.valueOf(apron_domestic[5])+" ");
        pm1.jLabel7.setText(" "+String.valueOf(apron_domestic[6])+" ");
        pm1.jLabel8.setText(" "+String.valueOf(apron_domestic[7])+" ");
        pm1.jLabel9.setText(" "+String.valueOf(apron_domestic[8])+" ");
        pm1.jLabel10.setText(" "+String.valueOf(apron_domestic[9])+" ");
        pm1.jLabel11.setText(" "+String.valueOf(apron_domestic[10])+" ");
        pm1.jLabel12.setText(" "+String.valueOf(apron_domestic[11])+" ");
        pm1.jLabel13.setText(" "+String.valueOf(apron_domestic[12])+" ");
        pm1.jLabel14.setText(" "+String.valueOf(apron_domestic[13])+" ");
        pm1.jLabel15.setText(" "+String.valueOf(apron_domestic[14])+" ");
        pm1.jLabel16.setText(" "+String.valueOf(apron_domestic[15])+" ");
        pm1.jLabel17.setText(" "+String.valueOf(apron_domestic[16])+" ");
        pm1.jLabel18.setText(" "+String.valueOf(apron_domestic[17])+" ");
        pm1.jLabel19.setText(" "+String.valueOf(apron_domestic[18])+" ");
        pm1.jLabel20.setText(" "+String.valueOf(apron_domestic[19])+" ");
        pm1.jLabel21.setText(" "+String.valueOf(apron_domestic[20])+" ");
        pm1.jLabel22.setText(" "+String.valueOf(apron_domestic[21])+" ");
        pm1.jLabel23.setText(" "+String.valueOf(apron_domestic[22])+" ");
        pm1.jLabel24.setText(" "+String.valueOf(apron_domestic[23])+" ");
        pm1.jLabel25.setText(" "+String.valueOf(apron_domestic[24])+" ");
        pm1.jLabel26.setText(" "+String.valueOf(apron_domestic[25])+" ");
        pm1.jLabel27.setText(" "+String.valueOf(apron_domestic[26])+" ");
        pm1.jLabel28.setText(" "+String.valueOf(apron_domestic[27])+" ");
        pm1.jLabel29.setText(" "+String.valueOf(apron_domestic[28])+" ");
        pm1.jLabel30.setText(" "+String.valueOf(apron_domestic[29])+" ");
        pm1.jLabel31.setText(" "+String.valueOf(apron_domestic[30])+" ");
        pm1.jLabel32.setText(" "+String.valueOf(apron_domestic[31])+" ");
        pm1.jLabel33.setText(" "+String.valueOf(apron_domestic[32])+" ");
        pm1.jLabel34.setText(" "+String.valueOf(apron_domestic[33])+" ");
        pm1.jLabel35.setText(" "+String.valueOf(apron_domestic[34])+" ");
        pm1.jLabel36.setText(" "+String.valueOf(apron_domestic[35])+" ");
        pm1.jLabel37.setText(" "+String.valueOf(apron_domestic[36])+" ");
        pm1.jLabel38.setText(" "+String.valueOf(apron_domestic[37])+" ");
        pm1.jLabel39.setText(" "+String.valueOf(apron_domestic[38])+" ");
        pm1.jLabel40.setText(" "+String.valueOf(apron_domestic[39])+" ");
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        pm2.setVisible(true);
        
        if(apron_international[0]!=0)
        {
            pm2.jLabel1.setForeground(java.awt.Color.red);
            pm2.jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel1.setForeground(java.awt.Color.green);
            pm2.jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[1]!=0)
        {
            pm2.jLabel2.setForeground(java.awt.Color.red);
            pm2.jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel2.setForeground(java.awt.Color.green);
            pm2.jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[2]!=0)
        {
            pm2.jLabel3.setForeground(java.awt.Color.red);
            pm2.jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel3.setForeground(java.awt.Color.green);
            pm2.jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[3]!=0)
        {
            pm2.jLabel4.setForeground(java.awt.Color.red);
            pm2.jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel4.setForeground(java.awt.Color.green);
            pm2.jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[4]!=0)
        {
            pm2.jLabel5.setForeground(java.awt.Color.red);
            pm2.jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel5.setForeground(java.awt.Color.green);
            pm2.jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[5]!=0)
        {
            pm2.jLabel6.setForeground(java.awt.Color.red);
            pm2.jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel6.setForeground(java.awt.Color.green);
            pm2.jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[6]!=0)
        {
            pm2.jLabel7.setForeground(java.awt.Color.red);
            pm2.jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel7.setForeground(java.awt.Color.green);
            pm2.jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[7]!=0)
        {
            pm2.jLabel8.setForeground(java.awt.Color.red);
            pm2.jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel8.setForeground(java.awt.Color.green);
            pm2.jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[8]!=0)
        {
            pm2.jLabel9.setForeground(java.awt.Color.red);
            pm2.jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel9.setForeground(java.awt.Color.green);
            pm2.jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[9]!=0)
        {
            pm2.jLabel10.setForeground(java.awt.Color.red);
            pm2.jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel10.setForeground(java.awt.Color.green);
            pm2.jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[10]!=0)
        {
            pm2.jLabel11.setForeground(java.awt.Color.red);
            pm2.jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel11.setForeground(java.awt.Color.green);
            pm2.jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[11]!=0)
        {
            pm2.jLabel12.setForeground(java.awt.Color.red);
            pm2.jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel12.setForeground(java.awt.Color.green);
            pm2.jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[12]!=0)
        {
            pm2.jLabel13.setForeground(java.awt.Color.red);
            pm2.jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel13.setForeground(java.awt.Color.green);
            pm2.jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[13]!=0)
        {
            pm2.jLabel14.setForeground(java.awt.Color.red);
            pm2.jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel14.setForeground(java.awt.Color.green);
            pm2.jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[14]!=0)
        {
            pm2.jLabel15.setForeground(java.awt.Color.red);
            pm2.jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel15.setForeground(java.awt.Color.green);
            pm2.jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[15]!=0)
        {
            pm2.jLabel16.setForeground(java.awt.Color.red);
            pm2.jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel16.setForeground(java.awt.Color.green);
            pm2.jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[16]!=0)
        {
            pm2.jLabel17.setForeground(java.awt.Color.red);
            pm2.jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel17.setForeground(java.awt.Color.green);
            pm2.jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[17]!=0)
        {
            pm2.jLabel18.setForeground(java.awt.Color.red);
            pm2.jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel18.setForeground(java.awt.Color.green);
            pm2.jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[18]!=0)
        {
            pm2.jLabel19.setForeground(java.awt.Color.red);
            pm2.jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel19.setForeground(java.awt.Color.green);
            pm2.jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[19]!=0)
        {
            pm2.jLabel20.setForeground(java.awt.Color.red);
            pm2.jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel20.setForeground(java.awt.Color.green);
            pm2.jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        
        if(apron_international[20]!=0)
        {
            pm2.jLabel21.setForeground(java.awt.Color.red);
            pm2.jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel21.setForeground(java.awt.Color.green);
            pm2.jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[21]!=0)
        {
            pm2.jLabel22.setForeground(java.awt.Color.red);
            pm2.jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel22.setForeground(java.awt.Color.green);
            pm2.jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[22]!=0)
        {
            pm2.jLabel23.setForeground(java.awt.Color.red);
            pm2.jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel23.setForeground(java.awt.Color.green);
            pm2.jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[23]!=0)
        {
            pm2.jLabel24.setForeground(java.awt.Color.red);
            pm2.jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel24.setForeground(java.awt.Color.green);
            pm2.jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[24]!=0)
        {
            pm2.jLabel25.setForeground(java.awt.Color.red);
            pm2.jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel25.setForeground(java.awt.Color.green);
            pm2.jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[25]!=0)
        {
            pm2.jLabel26.setForeground(java.awt.Color.red);
            pm2.jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel26.setForeground(java.awt.Color.green);
            pm2.jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[26]!=0)
        {
            pm2.jLabel27.setForeground(java.awt.Color.red);
            pm2.jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel27.setForeground(java.awt.Color.green);
            pm2.jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[27]!=0)
        {
            pm2.jLabel28.setForeground(java.awt.Color.red);
            pm2.jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel28.setForeground(java.awt.Color.green);
            pm2.jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[28]!=0)
        {
            pm2.jLabel29.setForeground(java.awt.Color.red);
            pm2.jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel29.setForeground(java.awt.Color.green);
            pm2.jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[29]!=0)
        {
            pm2.jLabel30.setForeground(java.awt.Color.red);
            pm2.jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel30.setForeground(java.awt.Color.green);
            pm2.jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[30]!=0)
        {
            pm2.jLabel31.setForeground(java.awt.Color.red);
            pm2.jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel31.setForeground(java.awt.Color.green);
            pm2.jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[31]!=0)
        {
            pm2.jLabel32.setForeground(java.awt.Color.red);
            pm2.jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel32.setForeground(java.awt.Color.green);
            pm2.jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[32]!=0)
        {
            pm2.jLabel33.setForeground(java.awt.Color.red);
            pm2.jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel33.setForeground(java.awt.Color.green);
            pm2.jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[33]!=0)
        {
            pm2.jLabel34.setForeground(java.awt.Color.red);
            pm2.jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel34.setForeground(java.awt.Color.green);
            pm2.jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[34]!=0)
        {
            pm2.jLabel35.setForeground(java.awt.Color.red);
            pm2.jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel35.setForeground(java.awt.Color.green);
            pm2.jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[35]!=0)
        {
            pm2.jLabel36.setForeground(java.awt.Color.red);
            pm2.jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel36.setForeground(java.awt.Color.green);
            pm2.jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[36]!=0)
        {
            pm2.jLabel37.setForeground(java.awt.Color.red);
            pm2.jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel37.setForeground(java.awt.Color.green);
            pm2.jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[37]!=0)
        {
            pm2.jLabel38.setForeground(java.awt.Color.red);
            pm2.jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel38.setForeground(java.awt.Color.green);
            pm2.jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[38]!=0)
        {
            pm2.jLabel39.setForeground(java.awt.Color.red);
            pm2.jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel39.setForeground(java.awt.Color.green);
            pm2.jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_international[39]!=0)
        {
            pm2.jLabel40.setForeground(java.awt.Color.red);
            pm2.jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm2.jLabel40.setForeground(java.awt.Color.green);
            pm2.jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        
        pm2.jLabel1.setText(" "+String.valueOf(apron_international[0])+" ");
        pm2.jLabel2.setText(" "+String.valueOf(apron_international[1])+" ");
        pm2.jLabel3.setText(" "+String.valueOf(apron_international[2])+" ");
        pm2.jLabel4.setText(" "+String.valueOf(apron_international[3])+" ");
        pm2.jLabel5.setText(" "+String.valueOf(apron_international[4])+" ");
        pm2.jLabel6.setText(" "+String.valueOf(apron_international[5])+" ");
        pm2.jLabel7.setText(" "+String.valueOf(apron_international[6])+" ");
        pm2.jLabel8.setText(" "+String.valueOf(apron_international[7])+" ");
        pm2.jLabel9.setText(" "+String.valueOf(apron_international[8])+" ");
        pm2.jLabel10.setText(" "+String.valueOf(apron_international[9])+" ");
        pm2.jLabel11.setText(" "+String.valueOf(apron_international[10])+" ");
        pm2.jLabel12.setText(" "+String.valueOf(apron_international[11])+" ");
        pm2.jLabel13.setText(" "+String.valueOf(apron_international[12])+" ");
        pm2.jLabel14.setText(" "+String.valueOf(apron_international[13])+" ");
        pm2.jLabel15.setText(" "+String.valueOf(apron_international[14])+" ");
        pm2.jLabel16.setText(" "+String.valueOf(apron_international[15])+" ");
        pm2.jLabel17.setText(" "+String.valueOf(apron_international[16])+" ");
        pm2.jLabel18.setText(" "+String.valueOf(apron_international[17])+" ");
        pm2.jLabel19.setText(" "+String.valueOf(apron_international[18])+" ");
        pm2.jLabel20.setText(" "+String.valueOf(apron_international[19])+" ");
        pm2.jLabel21.setText(" "+String.valueOf(apron_international[20])+" ");
        pm2.jLabel22.setText(" "+String.valueOf(apron_international[21])+" ");
        pm2.jLabel23.setText(" "+String.valueOf(apron_international[22])+" ");
        pm2.jLabel24.setText(" "+String.valueOf(apron_international[23])+" ");
        pm2.jLabel25.setText(" "+String.valueOf(apron_international[24])+" ");
        pm2.jLabel26.setText(" "+String.valueOf(apron_international[25])+" ");
        pm2.jLabel27.setText(" "+String.valueOf(apron_international[26])+" ");
        pm2.jLabel28.setText(" "+String.valueOf(apron_international[27])+" ");
        pm2.jLabel29.setText(" "+String.valueOf(apron_international[28])+" ");
        pm2.jLabel30.setText(" "+String.valueOf(apron_international[29])+" ");
        pm2.jLabel31.setText(" "+String.valueOf(apron_international[30])+" ");
        pm2.jLabel32.setText(" "+String.valueOf(apron_international[31])+" ");
        pm2.jLabel33.setText(" "+String.valueOf(apron_international[32])+" ");
        pm2.jLabel34.setText(" "+String.valueOf(apron_international[33])+" ");
        pm2.jLabel35.setText(" "+String.valueOf(apron_international[34])+" ");
        pm2.jLabel36.setText(" "+String.valueOf(apron_international[35])+" ");
        pm2.jLabel37.setText(" "+String.valueOf(apron_international[36])+" ");
        pm2.jLabel38.setText(" "+String.valueOf(apron_international[37])+" ");
        pm2.jLabel39.setText(" "+String.valueOf(apron_international[38])+" ");
        pm2.jLabel40.setText(" "+String.valueOf(apron_international[39])+" ");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        pm3.setVisible(true);
        
        if(apron_cargo[0]!=0)
        {
            pm3.jLabel1.setForeground(java.awt.Color.red);
            pm3.jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel1.setForeground(java.awt.Color.green);
            pm3.jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[1]!=0)
        {
            pm3.jLabel2.setForeground(java.awt.Color.red);
            pm3.jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel2.setForeground(java.awt.Color.green);
            pm3.jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[2]!=0)
        {
            pm3.jLabel3.setForeground(java.awt.Color.red);
            pm3.jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel3.setForeground(java.awt.Color.green);
            pm3.jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[3]!=0)
        {
            pm3.jLabel4.setForeground(java.awt.Color.red);
            pm3.jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel4.setForeground(java.awt.Color.green);
            pm3.jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[4]!=0)
        {
            pm3.jLabel5.setForeground(java.awt.Color.red);
            pm3.jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel5.setForeground(java.awt.Color.green);
            pm3.jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[5]!=0)
        {
            pm3.jLabel6.setForeground(java.awt.Color.red);
            pm3.jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel6.setForeground(java.awt.Color.green);
            pm3.jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[6]!=0)
        {
            pm3.jLabel7.setForeground(java.awt.Color.red);
            pm3.jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel7.setForeground(java.awt.Color.green);
            pm3.jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[7]!=0)
        {
            pm3.jLabel8.setForeground(java.awt.Color.red);
            pm3.jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel8.setForeground(java.awt.Color.green);
            pm3.jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[8]!=0)
        {
            pm3.jLabel9.setForeground(java.awt.Color.red);
            pm3.jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel9.setForeground(java.awt.Color.green);
            pm3.jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[9]!=0)
        {
            pm3.jLabel10.setForeground(java.awt.Color.red);
            pm3.jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel10.setForeground(java.awt.Color.green);
            pm3.jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[10]!=0)
        {
            pm3.jLabel11.setForeground(java.awt.Color.red);
            pm3.jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel11.setForeground(java.awt.Color.green);
            pm3.jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[11]!=0)
        {
            pm3.jLabel12.setForeground(java.awt.Color.red);
            pm3.jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel12.setForeground(java.awt.Color.green);
            pm3.jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[12]!=0)
        {
            pm3.jLabel13.setForeground(java.awt.Color.red);
            pm3.jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel13.setForeground(java.awt.Color.green);
            pm3.jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[13]!=0)
        {
            pm3.jLabel14.setForeground(java.awt.Color.red);
            pm3.jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel14.setForeground(java.awt.Color.green);
            pm3.jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[14]!=0)
        {
            pm3.jLabel15.setForeground(java.awt.Color.red);
            pm3.jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel15.setForeground(java.awt.Color.green);
            pm3.jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[15]!=0)
        {
            pm3.jLabel16.setForeground(java.awt.Color.red);
            pm3.jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel16.setForeground(java.awt.Color.green);
            pm3.jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[16]!=0)
        {
            pm3.jLabel17.setForeground(java.awt.Color.red);
            pm3.jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel17.setForeground(java.awt.Color.green);
            pm3.jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[17]!=0)
        {
            pm3.jLabel18.setForeground(java.awt.Color.red);
            pm3.jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel18.setForeground(java.awt.Color.green);
            pm3.jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[18]!=0)
        {
            pm3.jLabel19.setForeground(java.awt.Color.red);
            pm3.jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel19.setForeground(java.awt.Color.green);
            pm3.jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[19]!=0)
        {
            pm3.jLabel20.setForeground(java.awt.Color.red);
            pm3.jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel20.setForeground(java.awt.Color.green);
            pm3.jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        
        if(apron_cargo[20]!=0)
        {
            pm3.jLabel21.setForeground(java.awt.Color.red);
            pm3.jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel21.setForeground(java.awt.Color.green);
            pm3.jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[21]!=0)
        {
            pm3.jLabel22.setForeground(java.awt.Color.red);
            pm3.jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel22.setForeground(java.awt.Color.green);
            pm3.jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[22]!=0)
        {
            pm3.jLabel23.setForeground(java.awt.Color.red);
            pm3.jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel23.setForeground(java.awt.Color.green);
            pm3.jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[23]!=0)
        {
            pm3.jLabel24.setForeground(java.awt.Color.red);
            pm3.jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel24.setForeground(java.awt.Color.green);
            pm3.jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[24]!=0)
        {
            pm3.jLabel25.setForeground(java.awt.Color.red);
            pm3.jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel25.setForeground(java.awt.Color.green);
            pm3.jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[25]!=0)
        {
            pm3.jLabel26.setForeground(java.awt.Color.red);
            pm3.jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel26.setForeground(java.awt.Color.green);
            pm3.jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[26]!=0)
        {
            pm3.jLabel27.setForeground(java.awt.Color.red);
            pm3.jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel27.setForeground(java.awt.Color.green);
            pm3.jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[27]!=0)
        {
            pm3.jLabel28.setForeground(java.awt.Color.red);
            pm3.jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel28.setForeground(java.awt.Color.green);
            pm3.jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[28]!=0)
        {
            pm3.jLabel29.setForeground(java.awt.Color.red);
            pm3.jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel29.setForeground(java.awt.Color.green);
            pm3.jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[29]!=0)
        {
            pm3.jLabel30.setForeground(java.awt.Color.red);
            pm3.jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel30.setForeground(java.awt.Color.green);
            pm3.jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[30]!=0)
        {
            pm3.jLabel31.setForeground(java.awt.Color.red);
            pm3.jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel31.setForeground(java.awt.Color.green);
            pm3.jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[31]!=0)
        {
            pm3.jLabel32.setForeground(java.awt.Color.red);
            pm3.jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel32.setForeground(java.awt.Color.green);
            pm3.jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[32]!=0)
        {
            pm3.jLabel33.setForeground(java.awt.Color.red);
            pm3.jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel33.setForeground(java.awt.Color.green);
            pm3.jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[33]!=0)
        {
            pm3.jLabel34.setForeground(java.awt.Color.red);
            pm3.jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel34.setForeground(java.awt.Color.green);
            pm3.jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[34]!=0)
        {
            pm3.jLabel35.setForeground(java.awt.Color.red);
            pm3.jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel35.setForeground(java.awt.Color.green);
            pm3.jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[35]!=0)
        {
            pm3.jLabel36.setForeground(java.awt.Color.red);
            pm3.jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel36.setForeground(java.awt.Color.green);
            pm3.jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[36]!=0)
        {
            pm3.jLabel37.setForeground(java.awt.Color.red);
            pm3.jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel37.setForeground(java.awt.Color.green);
            pm3.jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[37]!=0)
        {
            pm3.jLabel38.setForeground(java.awt.Color.red);
            pm3.jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel38.setForeground(java.awt.Color.green);
            pm3.jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[38]!=0)
        {
            pm3.jLabel39.setForeground(java.awt.Color.red);
            pm3.jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel39.setForeground(java.awt.Color.green);
            pm3.jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        if(apron_cargo[39]!=0)
        {
            pm3.jLabel40.setForeground(java.awt.Color.red);
            pm3.jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        }
        else
        {
            pm3.jLabel40.setForeground(java.awt.Color.green);
            pm3.jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        }
        
        pm3.jLabel1.setText(" "+String.valueOf(apron_cargo[0])+" ");
        pm3.jLabel2.setText(" "+String.valueOf(apron_cargo[1])+" ");
        pm3.jLabel3.setText(" "+String.valueOf(apron_cargo[2])+" ");
        pm3.jLabel4.setText(" "+String.valueOf(apron_cargo[3])+" ");
        pm3.jLabel5.setText(" "+String.valueOf(apron_cargo[4])+" ");
        pm3.jLabel6.setText(" "+String.valueOf(apron_cargo[5])+" ");
        pm3.jLabel7.setText(" "+String.valueOf(apron_cargo[6])+" ");
        pm3.jLabel8.setText(" "+String.valueOf(apron_cargo[7])+" ");
        pm3.jLabel9.setText(" "+String.valueOf(apron_cargo[8])+" ");
        pm3.jLabel10.setText(" "+String.valueOf(apron_cargo[9])+" ");
        pm3.jLabel11.setText(" "+String.valueOf(apron_cargo[10])+" ");
        pm3.jLabel12.setText(" "+String.valueOf(apron_cargo[11])+" ");
        pm3.jLabel13.setText(" "+String.valueOf(apron_cargo[12])+" ");
        pm3.jLabel14.setText(" "+String.valueOf(apron_cargo[13])+" ");
        pm3.jLabel15.setText(" "+String.valueOf(apron_cargo[14])+" ");
        pm3.jLabel16.setText(" "+String.valueOf(apron_cargo[15])+" ");
        pm3.jLabel17.setText(" "+String.valueOf(apron_cargo[16])+" ");
        pm3.jLabel18.setText(" "+String.valueOf(apron_cargo[17])+" ");
        pm3.jLabel19.setText(" "+String.valueOf(apron_cargo[18])+" ");
        pm3.jLabel20.setText(" "+String.valueOf(apron_cargo[19])+" ");
        pm3.jLabel21.setText(" "+String.valueOf(apron_cargo[20])+" ");
        pm3.jLabel22.setText(" "+String.valueOf(apron_cargo[21])+" ");
        pm3.jLabel23.setText(" "+String.valueOf(apron_cargo[22])+" ");
        pm3.jLabel24.setText(" "+String.valueOf(apron_cargo[23])+" ");
        pm3.jLabel25.setText(" "+String.valueOf(apron_cargo[24])+" ");
        pm3.jLabel26.setText(" "+String.valueOf(apron_cargo[25])+" ");
        pm3.jLabel27.setText(" "+String.valueOf(apron_cargo[26])+" ");
        pm3.jLabel28.setText(" "+String.valueOf(apron_cargo[27])+" ");
        pm3.jLabel29.setText(" "+String.valueOf(apron_cargo[28])+" ");
        pm3.jLabel30.setText(" "+String.valueOf(apron_cargo[29])+" ");
        pm3.jLabel31.setText(" "+String.valueOf(apron_cargo[30])+" ");
        pm3.jLabel32.setText(" "+String.valueOf(apron_cargo[31])+" ");
        pm3.jLabel33.setText(" "+String.valueOf(apron_cargo[32])+" ");
        pm3.jLabel34.setText(" "+String.valueOf(apron_cargo[33])+" ");
        pm3.jLabel35.setText(" "+String.valueOf(apron_cargo[34])+" ");
        pm3.jLabel36.setText(" "+String.valueOf(apron_cargo[35])+" ");
        pm3.jLabel37.setText(" "+String.valueOf(apron_cargo[36])+" ");
        pm3.jLabel38.setText(" "+String.valueOf(apron_cargo[37])+" ");
        pm3.jLabel39.setText(" "+String.valueOf(apron_cargo[38])+" ");
        pm3.jLabel40.setText(" "+String.valueOf(apron_cargo[39])+" ");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        remove r=new remove();
        r.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        NewPlane np=new NewPlane();
        np.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        Register r=new Register();
        r.setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Unregister un=new Unregister();
        un.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Removedat rd=new Removedat();
        rd.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Messages ms=new Messages();
        ms.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        ActivityLog al=new ActivityLog();
        al.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Emergency em=new Emergency();
        em.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
